import type { JSX } from 'react'
import {
    RealEstateArt,
    AutomobileArt,
    EducationArt,
    FinanceArt,
    BusinessArt,
    HomeArt,
    ConsumerArt,
    JewellersArt,
    GarmentArt,
    RestaurantArt,
    ConstructionArt,
    MedicalArt,
    ElectronicsArt,
    BeautyArt,
    EducationBizArt,
    RealEstateBizArt,
    TravelArt,
    AgricultureArt,
    FurnitureArt,
    PrintingArt,
    IndustrialArt,
    ElectricalArt,
    PlasticArt,
    LogisticsArt,
    EventsArt,
    SecurityArt,
    SportsArt,
    PetArt,
    WholesaleArt,
} from '@/components/icons'

const ART_MAP: Record<string, () => JSX.Element> = {
    'Real Estate Leads': RealEstateArt,
    'Automobile Leads': AutomobileArt,
    'Education Leads': EducationArt,
    'Finance Leads': FinanceArt,
    'Business Leads': BusinessArt,
    'Home & Lifestyle Leads': HomeArt,
    'Consumer Interest Leads': ConsumerArt,
    Jewellers: JewellersArt,
    'Garment & Textile': GarmentArt,
    'Restaurants & Food Businesses': RestaurantArt,
    'Construction & Building Material': ConstructionArt,
    'Automobile Businesses': AutomobileArt,
    'Medical & Healthcare': MedicalArt,
    'Electronics Businesses': ElectronicsArt,
    'Beauty & Personal Care': BeautyArt,
    'Education Businesses': EducationBizArt,
    'Real Estate': RealEstateBizArt,
    'Travel & Hospitality': TravelArt,
    'Agriculture & Farming': AgricultureArt,
    'Home & Furniture': FurnitureArt,
    'Printing & Packaging': PrintingArt,
    'Industrial & Machinery': IndustrialArt,
    'Electrical Businesses': ElectricalArt,
    'Plastic & Polymer': PlasticArt,
    'Logistics & Transport': LogisticsArt,
    'Events & Media': EventsArt,
    'Security & Safety': SecurityArt,
    'Sports & Fitness': SportsArt,
    'Pet Businesses': PetArt,
    'Wholesale Markets': WholesaleArt,
}

export default function CategoryArt({ title }: { title: string }) {
    const Art = ART_MAP[title] ?? WholesaleArt
    return <Art />
}